return {
  "akinsho/toggleterm.nvim",
  enabled = false,
  config = true,
  cmd = "ToggleTerm",
  keys = { { "<C-t>", "<cmd>ToggleTerm<cr>", desc = "Toggle floating terminal" } },
  opts = {
    open_mapping = [[<C-t>]],
    size = 15,
    auto_scroll = true,
    direction = "float",
    shade_filetypes = {},
    hide_numbers = true,
    insert_mappings = true,
    terminal_mappings = true,
    start_in_insert = true,
    close_on_exit = true,
    autochdir = true,
  },
}
